import type { ThemeDefinition } from '../types/theme.types';

export const THEMES: ThemeDefinition[] = [
  {
    id: 'classic-lantern',
    name: 'Classic Lantern',
    description: 'Warm amber glow, traditional star lantern aesthetic',
    textureId: 'classic-lantern',
    presetId: 'studio',
    emissiveColor: '#ff8844',
    emissiveIntensity: 1.0,
    glowColor: '#ff6633',
    particleColor: '#ffaa55',
    ambientColor: '#1c1c24',
    keyLightColor: '#ffffff',
    fillLightColor: '#ffffff',
    backgroundColor: '#1c1c24',
  },
  {
    id: 'crimson-ember',
    name: 'Crimson Ember',
    description: 'Deep reds and oranges, smoldering ember aesthetic',
    textureId: 'crimson-ember',
    presetId: 'living-room',
    emissiveColor: '#ff2200',
    emissiveIntensity: 1.2,
    glowColor: '#ff3300',
    particleColor: '#ff4444',
    ambientColor: '#2a1810',
    keyLightColor: '#ffaa88',
    fillLightColor: '#ff8844',
    backgroundColor: '#2a1810',
  },
  {
    id: 'deep-azure',
    name: 'Deep Azure',
    description: 'Cool blues and teals, celestial ice aesthetic',
    textureId: 'deep-azure',
    presetId: 'studio',
    emissiveColor: '#4488ff',
    emissiveIntensity: 1.0,
    glowColor: '#3366ff',
    particleColor: '#6699ff',
    ambientColor: '#101828',
    keyLightColor: '#cceeff',
    fillLightColor: '#88bbff',
    backgroundColor: '#101828',
  },
  {
    id: 'solar-gold',
    name: 'Solar Gold',
    description: 'Radiant golds and warm whites, solar flare aesthetic',
    textureId: 'solar-gold',
    presetId: 'living-room',
    emissiveColor: '#ffcc00',
    emissiveIntensity: 1.4,
    glowColor: '#ffaa00',
    particleColor: '#ffdd55',
    ambientColor: '#1c1810',
    keyLightColor: '#ffeecc',
    fillLightColor: '#ffddaa',
    backgroundColor: '#1c1810',
  },
  {
    id: 'aurora',
    name: 'Aurora',
    description: 'Greens and purples, northern lights aesthetic',
    textureId: 'classic-lantern',
    presetId: 'studio',
    emissiveColor: '#44ff88',
    emissiveIntensity: 1.3,
    glowColor: '#66ffaa',
    particleColor: '#88ffcc',
    ambientColor: '#0a1018',
    keyLightColor: '#ccffdd',
    fillLightColor: '#aaccff',
    backgroundColor: '#0a1018',
  },
  {
    id: 'ocean',
    name: 'Ocean',
    description: 'Deep blues and cyan, underwater luminescence aesthetic',
    textureId: 'deep-azure',
    presetId: 'studio',
    emissiveColor: '#00ccff',
    emissiveIntensity: 1.1,
    glowColor: '#0099ff',
    particleColor: '#33ccff',
    ambientColor: '#0a1420',
    keyLightColor: '#aaddff',
    fillLightColor: '#77bbff',
    backgroundColor: '#0a1420',
  },
];

export function getThemeById(id: string): ThemeDefinition | undefined {
  return THEMES.find((t) => t.id === id);
}
